Program Flow:
1. Logging ID Generation, Renaming Columns, ...
2. Data Cleaning

In [361]:
import pandas as pd
import numpy as np

Logging Components :    

1. check if dataframe is empty    (T/F)
2. check if dataframe h or v orie (H/V)

3. Check if has ID column         (0-1)
4. check if has missing values    (0-1)
5. check if has duplicate values  (0-1)

6. check if has format issues     (0-1)
7. check if has datatype issues   (0-1)
8. check if only string components(0-1)

9. check if has outliers by IQR   (0-1)
10. check if need standardization  (0-1)
11. check for data imbalance gini  (0-1)

12. check for emails column       (0-1)
13. check for address column      (0-1)
14. check for age column          (0-1)
15. check for phone number column (0-1)
16. check for occupation column   (0-1)
17. check for education column    (0-1)
18. check for salary column       (0-1)
19. check for time column         (0-1)
20. check for sales column        (0-1)

21. count number of row           (row_sum + /)
22. count number of col           (col_sum + /)
23. count number of data          (data_sum)

24. Regression type               (T,S,C) timeseries, simple, complex
25. Clustering type               (D,C,O) density, centroid, other
26. Classification type           (B,M,S) binary,multiclass,standard

27. need further checking?        (1-100) a = minor, z = critical

In [362]:
config_list = [5 ,0,0,0,0,0,0,0,0]
# 0 -> amount of datatypes available in language

In [363]:
## Check Functions ##

def CheckForDtype(dataframe):
  df = dataframe
  dtypeSeries = df.dtypes
  colnameSeries = df.columns.values
  index = 0
  dtype_issue = 0
  for a in dtypeSeries:
    if(a == "object"):
      dtype_issue = 1
    else:
      index = index + 1
  return dtype_issue

def CheckForMissing(dataframe):
  df = dataframe
  isNullSeries = df.isnull().any(axis=1)
  for a in isNullSeries:
    if(a == True):
      null = True
      break
    else:
      null = False
  return null

def CheckForDuplicated(dataframe):
  df = dataframe
  isDuplicatedSeries = df.duplicated()
  for a in isDuplicatedSeries:
    if(a == True):
      duplicate = True
      break
    else:
      duplicate = False
  return duplicate

def CheckForIdColumn(dataframe):
  df = dataframe
  col_names = df.columns.values
  index = 0
  for a in col_names:
    if(a == 'ID' or a == 'id' or a == "Id" or a == 'iD'):
      id = True
      break
    elif(a.includes("_ID") or a.includes('_id') or a.includes('_Id') or a.includes('_iD')):
      id = True
      break
    else:
      id = False
      index = index + 1
  return index

def CheckForCompleteIncrementalColumn(dataframe,index):
  df = dataframe

  row_count = (len(df)) + 1
  expected_row_id = set(range(1,row_count))
  actual_row_id = set(df.columns[index])
  is_incremental = expected_row_id == actual_row_id

  if(is_incremental == True):
    increment = 1
  else:
    increment = 0

  return increment

def CheckDataAlignment(dataframe):
  df = dataframe
  alignment = "WIP"
  # Check if dataframe is horizontal or vertically aligned
  return alignment

def CheckForCompleteUniqueColumn(dataframe,index):
  df = dataframe
  col_name = df.columns[index]
  row_id = pd.Series(df[col_name].map(type))
  unique_row_id = pd.Series(row_id.unique())
  n_row_id = len(row_id)
  n_urow_id = len(unique_row_id)

  if(n_row_id == n_urow_id):
    completelyUnique = 1
  else:
    completelyUnique = 0
  return completelyUnique

In [364]:
## Main Solve Functions ##

def MakeIdColumn(dataframe):
  df = dataframe

  df = df.reset_index()
  df = df.rename(columns = {'index':'row_id'})

  return df

def HandleMissingData(dataframe):
  df = dataframe
  return df

def NoteMissingData(dataframe):
  df = dataframe
  Note = 0
  return Note

def NoteDuplicatedData(dataframe):
  df = dataframe
  Note = 0
  return Note

def NoteColumnMinorities(dataframe):
  df = dataframe
  Note = 0
  return Note

def HandleDuplicatedData(dataframe):
  df = dataframe
  return df

def ConformAllColumnsToMajority(dataframe):
  df = dataframe
  dtypeSeries = df.dtypes
  colnameSeries = df.columns.values
  index = 0
  for a in dtypeSeries:
    if(a == "object"):
      col_name = colnameSeries[index]
      df_dtypes = pd.Series(df[col_name].map(type))
      df_dtypes_unique = pd.Series(df_dtypes.unique())
      string_series = pd.Series(df_dtypes, dtype="string")
      df_dtypes_sorted = string_series.sort_values()
      conv_df_dtypes_unique = df_dtypes_unique.astype(str)
      conv_df_dtypes = df_dtypes.astype(str)
      conv_df_dtypes_sorted = df_dtypes_sorted.astype(str)

      datatypes = config_list[0]
      counter = [0] * datatypes

      counter = CountRowsPerDatatype(counter, conv_df_dtypes_sorted, conv_df_dtypes_unique)
      majority_value = GetMajorityValue(counter, datatypes, conv_df_dtypes_unique)

      if(majority_value == "<class 'str'>"):
        df[col_name] = df[col_name].astype("string")

      elif(majority_value == "<class 'int'>"):
        df[col_name] = df[col_name].astype("Int64")

      elif(majority_value == "<class 'float'>"):
        df[col_name] = df[col_name].astype("Float64")

      elif(majority_value == "<class 'complex'>"):
        df[col_name] = df[col_name].astype(complex)

      elif(majority_value == "<class 'bool'>"):
        df[col_name] = df[col_name].astype("boolean")

    else:
      index = index + 1

  return df

In [365]:
## Auxillary Functions ##

def RenameIdColumn(dataframe,index):
  df = dataframe
  df = df.rename(columns={df.columns[index] : "row_id"})

  return df

def CountRowsPerDatatype(array, data_list, data_list_unique):

  counter = array

  for b in data_list:
        x = 0
        for c in data_list_unique:
          if(b == c):
            counter[x] = counter[x] + 1
            break
          else:
            x = x + 1

  return counter

def GetMajorityValue(array,datatypes,data_list_unique):

  counter = array
  conv_df_dtypes_unique = data_list_unique

  new_counter = counter.copy()
  new_counter.sort()
  majority_amount = new_counter[-1]

  m = 0
  for d in counter:
    if(counter[m] == majority_amount and m<datatypes):
      majority_index = m
      break
    else:
      m = m + 1

  majority_value = conv_df_dtypes_unique[majority_index]
  return majority_value


def PrintCounter(array):

  x = 0
  counter = array

  for d in counter:
    print(counter[x])
    x = x + 1

In [366]:
missing_values = ['NA', ' ', 'none','null','NULL','na','Na','Null','  ','.',',','   ']
df = pd.read_csv('Test.csv',na_values = missing_values)

if(df.empty == True):
  isEmpty = 1
else:
  isEmpty = 0

  if(CheckDataAlignment(df) == True):
    isHorizontal = 1
  else:
    isHorizontal = 0

  id_index = CheckForIdColumn(df)
  if((id_index == 0 and CheckForCompleteIncrementalColumn(df,id_index) == True) or CheckForCompleteUniqueColumn(df,id_index)):
    df = RenameIdColumn(df,id_index)
    hasId = 1
  else:
    df = MakeIdColumn(df)
    hasId = 0

  if(CheckForMissing(df) == True):
    df = HandleMissingData(df)
    hasMissing = 1
  else:
    hasMissing = 0

  if(CheckForDuplicated(df) == True):
    df = HandleDuplicatedData(df)
    hasDuplicate = 1
  else:
    hasDuplicate = 0

  if(CheckForDtype(df) == True):
    df = ConformAllColumnsToMajority(df)
    hasDtypeObj = 1
  else:
    hasDtypeObj = 0

In [367]:
df.head(100)

,row_id,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1
0,0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6
1,1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6
2,2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6
3,3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6
4,4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6
...,...,...,...,...,...,...,...,...,...,...,...
95,95,459290,Female,Yes,70,Yes,Doctor,1.0,Average,2.0,Cat_6
96,96,459292,Male,No,46,Yes,Artist,0.0,Low,2.0,Cat_6
97,97,459293,Male,No,21,No,Healthcare,NaN,Low,NaN,Cat_1
98,98,459296,Male,Yes,70,Yes,Artist,0.0,Average,2.0,Cat_6
99,99,459300,Female,Yes,61,Yes,Artist,1.0,Low,NaN,Cat_6